GptLark:
  LLMName: "WXYY"
  Key: "your_key"
  EndPoint: "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/completions_pro"
  AppSecret: "your_app_secret"

App:
  HttpPort: 8080
  WebSocketPort: 8089
  RpcPort: 9001
  HttpUrl: 127.0.0.1:8080
  WebSocketUrl:  127.0.0.1:8089

  redis:
    addr: "localhost:6379"
    password: ""
    DB: 0
    poolSize: 30
    minIdleConns: 30